name: Build & Release Book
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version of the gitbook, such as v1.1.1'
        required: true
        default: 'v1.1.0'

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  get-upload-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo bash ./getuploadurl.sh ${{ github.event.inputs.version }} ${{ secrets.GITHUB_TOKEN }} | xargs -I {} echo "upload-url={}" >> $GITHUB_OUTPUT
        id: upload-url
    outputs:
      upload-url: ${{ steps.upload-url.outputs.upload-url }} 
  
  build:
    needs: get-upload-url
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Checkout main source
        uses: actions/checkout@v2
